"""Add broker_connection, position, portfolio_snapshot tables

Revision ID: a1b2c3d4e5f6
Revises: f73260195f1c
Create Date: 2026-04-24 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'f73260195f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_connections',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('broker_type', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('flex_token', sa.Text(), nullable=True),
        sa.Column('flex_query_id', sa.Text(), nullable=True),
        sa.Column('account_id', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('broker_connection_id', sa.Integer(), nullable=False),
        sa.Column('total_value', sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column('cash_balance', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('daily_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('daily_pnl_pct', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('broker_connection_id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=20), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('asset_class', sa.String(length=50), nullable=True),
        sa.Column('sector', sa.String(length=100), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=True),
        sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('market_price', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('portfolio_snapshots')
    op.drop_table('broker_connections')
    # ### end Alembic commands ###
